# =====================================================================================================
#    _____        __               _ _           _                     _   _
#   |  __ \      / _|             | | |    /   /| |                   | | | |
#   | |  | | ___| |_ ___ _ __   __| | |    _   _| |_ _______ _ __ __ _| |_| |__
#   | |  | |/ _ \  _/ _ \ '_ \ / _` | |   | | | | __|_  / _ \ '__/ _` | __| '_ \
#   | |__| |  __/ ||  __/ | | | (_| | |___| |_| | |_ / /  __/ | | (_| | |_| | | |
#   |_____/ \___|_| \___|_| |_|\__,_|______\__,_|\__/___\___|_|  \__,_|\__|_| |_|
#
# =====================================================================================================
# © Dwarslooper 2023
# =====================================================================================================

# The language the plugin, default "en_us". Can be configured in-game as well.
language: de_de

# Minimum amount of spawns that have to be set to register an arena
min_enemy_spawns: 10

# Game-Difficulty. This feature is experimental and may cause bugs when modifying!
difficulty: 4

# Ticks between specific actions to prevent lag
ratelimit: 40

# If the player(s) should be notified when a protester dies
notify-death: false

# If short-commands like /start, /join <arena> or /leave should be enabled
short-commands: false

# If the players inventory should be saved. Useful when having items in your inventory
inventory-manager: true

# Commands which should be blocked ingame (without "/"); leave empty to disable
blocked-commands:
  - ec
  - enderchest

# How many points to add to the balance when killing an enemy
points-on-kill: 2

# How many points to lose when a protester dies
points-on-death: 4

# If picking up mud should be enabled
pickup-mud: true

# How many points assets should generate (set to 0 to disable)
points-from-assets: 0

# The delay in which assets should generate points in ticks (points have to be greater than 0)
asset-generate-points-delay: 40

# Delay in which enemies should spawn (in ticks!)
spawn-delay: 80

# ================================================
# Used by the plugin internally. Do not modify!
# ================================================

has-init: false
version: 8

# That's it! You've reached the end! But.. Where's the dragon?